db.rest.find();
db.rest.find({}, {"restaurante_id":1, "name":1, "borough":1, "cuisine":1});
db.rest.find({}, {"_id":0, "restaurante_id":1, "name":1, "borough":1, "cuisine":1});
db.rest.find({}, {"restaurant_id":1, "name":1, "borough":1, "address.zipcode":1, "_id":0});
db.rest.find({borough: "Bronx"}, {name:1, _id:0});
db.rest.find({borough: "Bronx"}, {name:1, _id:0}).limit(5);
db.rest.find({borough: "Bronx"}, {name:1, _id:0}).skip(5).limit(5);
db.rest.find({'grades.score': {$gt: 90}});
db.rest.find({'grades.score': {$gt: 80, $lt: 100}});
db.rest.find({'address.coord.0': {$lt: -95.754168}});
db.rest.find({$and:[{'cuisine': {$ne: "American "}}, {'grades.score': {$gt: 70}}, {'address.coord.1': {$lt: -65.754168}}]});
db.rest.find({'cuisine': {$ne: "American "}, 'grades.score': {$gt: 70}, 'address.coord.0': {$lt: -65.754168}});
db.rest.find({'cuisine': {$ne: "American "}, 'grades.grade': {$eq: "A"}, 'borough': {$ne: "Brooklyn"}}).sort({'cuisine': -1});
db.rest.find({name: /^Wil/}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1});
db.rest.find({name: /ces$/}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1});
db.rest.find({name: /Reg/}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1});
db.rest.find({'borough': 'Bronx', 'cuisine': {$in: ["American ", "Chinese"]}});
db.rest.find({'borough': {$in: ["Staten Island", "Queens", "Bronx", "Brooklyn"]}}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1});
db.rest.find({'borough': {$nin: ["Staten Island", "Queens", "Bronx", "Brooklyn"]}}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1});
db.rest.find({'grades.score': {$lt: 10}}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1});